### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by ghost** [thomastkim/laravel-online-users#7]
In Laravel 5.2 I have this error:

`Call to undefined method Illuminate\Database\Query\Builder::users()`

Have anyone a idea?

**Comment by ghost** [comment]
#push

**Comment by gabdsg** [comment]
Same problem

**Comment by bfblackjack** [comment]
Same here

**Comment by TheNerka** [comment]
Help!

**Comment by KodeStar** [comment]
5.2 doesn't seem to have the config items the package is looking for, try adding 
    'model' => App\User::class,
to the top of /pp/config/auth ( after return [ )

there is a pull request by another user that changes where it looks for the model, but that was submitted 3 months ago and still hasn't beed added

_edit_ also the documentation uses "users" but the trait seems to use "user"

**Comment by thomastkim** [comment]
Hey guys, sorry for the late response. I have been busy, but I will push an update soon. L5.2 introduced a lot of changes, and unfortunately, it's a bit more than a simple config change. On the bright side, we no longer need to extend the database session handler, and it provides us with extra details like the ip address and user agent.

Also, `user()` simply defines the `belongsTo` relationship. Because of how eager loading works, that will still get all activities, including guests and users. `users()`, `usersByMinutes()`, `usersBySeconds()`, etc. are the proper methods as stated in the documentation to query only the necessary activities, based on the specified time constraints.

Anyway, I will try to push the new changes soon (when I get home tonight).

**Comment by thomastkim** [comment]
I've pushed support for 5.2. Please try updating to version 1.1 and then running `composer update`. :smile:
